// Configuration (Optional - only needed for local testing)
// For production, projects are loaded from projects.json generated by GitHub Actions
// This file can be safely committed as it doesn't contain sensitive tokens

window.config = {
    // GitHub Personal Access Token (ONLY for local testing)
    // Leave empty for production - GitHub Actions will handle fetching
    // Generate one at: https://github.com/settings/tokens (if needed for local testing)
    githubToken: '',
    
    // Filtering options (these are handled by GitHub Actions workflow)
    // These are kept here for local testing fallback only
    excludeForks: true,        // Exclude forked repositories
    excludeArchived: true,      // Exclude archived repositories
    excludePrivate: false,      // Set to true to exclude private repositories
    
    // List of repository names to exclude from the portfolio (case-insensitive)
    // This should match the exclusion list in .github/workflows/update-projects.yml
    excludeRepos: [
        'FSRA',
        'Som WorkAssist',
        'SidharthRao.github.io',
        'Important Scripts Practice',
        'National Statistics Automation',
        'Project Rogue',
        'CAO PowerBI Project',
        'GenAI CustomerServiceBot',
        'ExecutorAssist And ImportantScript',
        'ExpenseAccrual',
        'MSDS Projects And Concepts',
        'Automation Treasury',
        'EndToEnd VendorWHTActivity',
        'Vendor WHT',
        'RCM InvoiceGeneration',
        'TimeSeries SpecializedModels',
        'AuditAssistant ChatBot',
        'Model Fine Tuning',
        'Project Dash',
        'Custom Voicebot',
        'S4 HanaRecon',
        'ML-Applicability-POC-Projects',
        'Working-with-PDF-Files',
        'Text_Analysis-Reclass',
        'IC_Revenue',
        'IC_Automation',
        'Finalyzer_DataIngestion2.0',
        'Expense_Classification-and-Reclass',
        'KPI-Dashboad',
        'AAAMLP GuideForProjectFolders',
        'Arithmetic_Algo',
        'Base_ML-Scripts',
        'Natural-Language-Processing',
        'Intel-AI---MLOps',
        'Flask_Basics',
        'StockMarketAalysis',
        'ICA WHT Reporting',
        'expense_reclassification',
        'Applying-feature-selection'
    ]
};

