// Configuration (Optional - only needed for local testing)
// For production, projects are loaded from projects.json generated by GitHub Actions
// This file can be safely committed as it doesn't contain sensitive tokens

window.config = {
    // GitHub Personal Access Token (ONLY for local testing)
    // Leave empty for production - GitHub Actions will handle fetching
    // Generate one at: https://github.com/settings/tokens (if needed for local testing)
    githubToken: '',
    
    // Filtering options (these are handled by GitHub Actions workflow)
    // These are kept here for local testing fallback only
    excludeForks: true,        // Exclude forked repositories
    excludeArchived: true,      // Exclude archived repositories
    excludePrivate: false       // Set to true to exclude private repositories
};

