// Configuration from config.js (optional, only for local testing)
let config = {
    excludeForks: true,
    excludeArchived: true,
    excludePrivate: false
};

// Initialize configuration (optional)
if (typeof window.config !== 'undefined') {
    config = { ...config, ...window.config };
}

// Load projects from JSON file (generated by GitHub Actions)
async function loadProjectsFromJSON() {
    try {
        const response = await fetch('projects.json');
        if (!response.ok) {
            throw new Error('projects.json not found');
        }
        const projects = await response.json();
        return projects;
    } catch (error) {
        console.warn('Could not load projects.json:', error);
        return null;
    }
}

// Fallback: GitHub API Functions (for local testing only)
const GITHUB_API_BASE = 'https://api.github.com';

async function fetchRepositoriesFromAPI() {
    const url = `${GITHUB_API_BASE}/user/repos?type=all&per_page=100&sort=updated&direction=desc`;
    const headers = {
        'Accept': 'application/vnd.github.v3+json'
    };

    if (config.githubToken) {
        headers['Authorization'] = `token ${config.githubToken}`;
    }

    try {
        const response = await fetch(url, { headers });
        
        if (!response.ok) {
            if (response.status === 401) {
                throw new Error('Authentication failed. Please check your GitHub token.');
            }
            throw new Error(`GitHub API error: ${response.status} ${response.statusText}`);
        }

        const repos = await response.json();
        return repos;
    } catch (error) {
        console.error('Error fetching repositories:', error);
        throw error;
    }
}

// Data Processing Functions (for local testing fallback)
function filterRepositories(repos) {
    // Get exclusion list from config, default to empty array
    const excludeRepos = config.excludeRepos || [];
    
    return repos.filter(repo => {
        if (config.excludeForks && repo.fork) return false;
        if (config.excludeArchived && repo.archived) return false;
        if (config.excludePrivate && repo.private) return false;
        // Exclude specific repositories by name (case-insensitive)
        if (excludeRepos.some(excluded => repo.name.toLowerCase() === excluded.toLowerCase())) {
            return false;
        }
        return true;
    });
}

function formatDate(dateString) {
    if (!dateString) return 'N/A';
    const date = new Date(dateString);
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    return date.toLocaleDateString('en-US', options);
}

function getDateRange(createdAt, updatedAt) {
    if (!createdAt) return 'Date not available';
    
    const created = new Date(createdAt);
    const updated = new Date(updatedAt);
    
    const createdFormatted = created.toLocaleDateString('en-US', { year: 'numeric', month: 'short' });
    
    // If updated is significantly different from created, show range
    const daysDiff = Math.floor((updated - created) / (1000 * 60 * 60 * 24));
    
    if (daysDiff > 30) {
        const updatedFormatted = updated.toLocaleDateString('en-US', { year: 'numeric', month: 'short' });
        return `${createdFormatted} - ${updatedFormatted}`;
    }
    
    return `Started ${createdFormatted}`;
}

function createBusinessDescription(repo) {
    // Use existing description if it's business-friendly
    if (repo.description && repo.description.length > 0) {
        // Check if description seems technical (contains common tech terms)
        const technicalTerms = ['api', 'framework', 'library', 'npm', 'package', 'module', 'component', 'hook', 'utils'];
        const descriptionLower = repo.description.toLowerCase();
        const isTechnical = technicalTerms.some(term => descriptionLower.includes(term));
        
        if (!isTechnical || repo.description.length < 50) {
            return repo.description;
        }
    }
    
    // Generate business-friendly description
    const language = repo.language || 'Various technologies';
    const topics = repo.topics || [];
    
    let description = `A ${repo.private ? 'private' : 'public'} project`;
    
    if (topics.length > 0) {
        const businessTopics = topics.filter(topic => 
            !['javascript', 'typescript', 'python', 'java', 'react', 'node', 'api'].includes(topic.toLowerCase())
        );
        if (businessTopics.length > 0) {
            description += ` focused on ${businessTopics.slice(0, 2).join(' and ')}`;
        }
    }
    
    description += `. Built using ${language} and other modern technologies.`;
    
    return description;
}

function processRepository(repo) {
    return {
        id: repo.id,
        name: formatProjectName(repo.name),
        description: createBusinessDescription(repo),
        language: repo.language || 'Various',
        dateRange: getDateRange(repo.created_at, repo.updated_at),
        topics: repo.topics || [],
        url: repo.html_url,
        private: repo.private,
        updatedAt: repo.updated_at
    };
}

function formatProjectName(name) {
    // Convert kebab-case or snake_case to Title Case
    return name
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
}

// Rendering Functions
function renderProjects(projects) {
    const container = document.getElementById('projects-container');
    const loading = document.getElementById('loading');
    const error = document.getElementById('error');
    
    loading.style.display = 'none';
    error.style.display = 'none';
    
    if (!projects || projects.length === 0) {
        container.innerHTML = '<p style="text-align: center; color: var(--text-light);">No projects found.</p>';
        return;
    }
    
    // Sort projects by updated date (most recent first)
    projects.sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));
    
    container.innerHTML = projects.map(project => createProjectCard(project)).join('');
}

function createProjectCard(project) {
    const tags = project.topics.slice(0, 5).map(topic => 
        `<span class="tag">${topic}</span>`
    ).join('');
    
    const languageTag = project.language !== 'Various' 
        ? `<span class="tag tag--primary">${project.language}</span>` 
        : '';
    
    const allTags = languageTag + tags;
    
    return `
        <div class="project-card">
            <h2 class="project-card__title">${escapeHtml(project.name)}</h2>
            <p class="project-card__description">${escapeHtml(project.description)}</p>
            <div class="project-card__meta">
                <div class="meta-item">
                    <span class="meta-item__label">Period:</span>
                    <span>${escapeHtml(project.dateRange)}</span>
                </div>
                ${project.private ? '<div class="meta-item"><span class="meta-item__label">Type:</span><span>Private</span></div>' : ''}
            </div>
            ${allTags ? `<div class="project-card__tags">${allTags}</div>` : ''}
            ${project.url ? `<div class="project-card__link"><a href="${project.url}" target="_blank" rel="noopener noreferrer">View on GitHub →</a></div>` : ''}
        </div>
    `;
}

function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

function showError(message) {
    const loading = document.getElementById('loading');
    const error = document.getElementById('error');
    
    loading.style.display = 'none';
    error.style.display = 'block';
    error.querySelector('p').textContent = message;
}

// Initialize
async function init() {
    // Set current year in footer
    document.getElementById('current-year').textContent = new Date().getFullYear();
    
    try {
        // Try to load from projects.json first (generated by GitHub Actions)
        let projects = await loadProjectsFromJSON();
        
        if (!projects) {
            // Fallback: Use GitHub API (for local testing only)
            console.log('Loading from GitHub API (local testing mode)...');
            if (!config.githubToken) {
                showError('Projects data not available. The GitHub Actions workflow should generate projects.json automatically. For local testing, configure your token in config.js');
                return;
            }
            const repos = await fetchRepositoriesFromAPI();
            const filteredRepos = filterRepositories(repos);
            projects = filteredRepos.map(processRepository);
        }
        
        renderProjects(projects);
    } catch (error) {
        console.error('Initialization error:', error);
        showError(error.message || 'Failed to load projects. Please check your configuration and try again.');
    }
}

// Run when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
} else {
    init();
}

